"""
Core module for the Document Digitalization Platform.

This module contains the foundational models, configuration loaders,
and exceptions used throughout the platform.
"""

from .models import (
    # Enums
    DealStatus,
    DocumentSourceChannel,
    PipelineType,
    RunStatus,
    ReviewStatus,
    AttestationDecision,
    ValidationType,
    ValidationStatus,
    ExtractionMode,
    # Core models
    Deal,
    Document,
    DocumentNode,
    DocumentStructure,
    BoundingBox,
    Citation,
    ExtractedField,
    ExtractionRun,
    FieldOverride,
    Attestation,
    ReviewTask,
    DataPointValue,
    DataPointValidation,
    SectionDataPoints,
    GeneratedSection,
    GenerationRun,
    FieldRevision,
    RevisionHistory,
    WebhookDelivery,
)

from .config_loader import (
    ConfigLoader,
    ExtractionPipelineConfig,
    GenerationPipelineConfig,
    get_config_loader,
    load_extraction_config,
    load_generation_config,
)
from .schemas import (
    CitationOutput,
    ExtractedFieldOutput,
    ExtractionResultOutput,
    ExtractionCreateRequest,
    ExtractionCreateResponse,
    HealthStatus,
)
from .settings import Settings, get_settings

from .exceptions import (
    DocDigitalizationError,
    ConfigurationError,
    PipelineNotFoundError,
    InvalidConfigurationError,
    DocumentError,
    DocumentNotFoundError,
    DocumentProcessingError,
    UnsupportedDocumentTypeError,
    OCRError,
    ExtractionError,
    StructureExtractionError,
    FieldExtractionError,
    LowConfidenceError,
    AgentError,
    AgentBudgetExceededError,
    GenerationError,
    DataGatheringError,
    DataPointConflictError,
    SectionGenerationError,
    DocumentAssemblyError,
    WorkflowError,
    ReviewTaskNotFoundError,
    AttestationError,
    InvalidOverrideError,
    JustificationRequiredError,
    IntegrationError,
    DMSError,
    LLMError,
    WebhookError,
    DealError,
    DealNotFoundError,
    DocumentsNotReadyError,
)

__all__ = [
    # Enums
    "DealStatus",
    "DocumentSourceChannel",
    "PipelineType",
    "RunStatus",
    "ReviewStatus",
    "AttestationDecision",
    "ValidationType",
    "ValidationStatus",
    "ExtractionMode",
    # Core models
    "Deal",
    "Document",
    "DocumentNode",
    "DocumentStructure",
    "BoundingBox",
    "Citation",
    "ExtractedField",
    "ExtractionRun",
    "FieldOverride",
    "Attestation",
    "ReviewTask",
    "DataPointValue",
    "DataPointValidation",
    "SectionDataPoints",
    "GeneratedSection",
    "GenerationRun",
    "FieldRevision",
    "RevisionHistory",
    "WebhookDelivery",
    # Config
    "ConfigLoader",
    "ExtractionPipelineConfig",
    "GenerationPipelineConfig",
    "get_config_loader",
    "load_extraction_config",
    "load_generation_config",
    "CitationOutput",
    "ExtractedFieldOutput",
    "ExtractionResultOutput",
    "ExtractionCreateRequest",
    "ExtractionCreateResponse",
    "HealthStatus",
    "Settings",
    "get_settings",
    # Exceptions
    "DocDigitalizationError",
    "ConfigurationError",
    "PipelineNotFoundError",
    "InvalidConfigurationError",
    "DocumentError",
    "DocumentNotFoundError",
    "DocumentProcessingError",
    "UnsupportedDocumentTypeError",
    "OCRError",
    "ExtractionError",
    "StructureExtractionError",
    "FieldExtractionError",
    "LowConfidenceError",
    "AgentError",
    "AgentBudgetExceededError",
    "GenerationError",
    "DataGatheringError",
    "DataPointConflictError",
    "SectionGenerationError",
    "DocumentAssemblyError",
    "WorkflowError",
    "ReviewTaskNotFoundError",
    "AttestationError",
    "InvalidOverrideError",
    "JustificationRequiredError",
    "IntegrationError",
    "DMSError",
    "LLMError",
    "WebhookError",
    "DealError",
    "DealNotFoundError",
    "DocumentsNotReadyError",
]
